# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
!pip install mdutils

In [2]:
import mdutils as md

In [3]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [4]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
print(np.__version__)

1.23.5


In [6]:
print(np.show_config())

openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFI

#### 3. Create a null vector of size 10 (★☆☆)

In [7]:
null_vector=np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [8]:
arr = np.zeros(10)
print(arr.size * arr.itemsize)  # This gives the memory size in bytes

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [9]:
# get the documentation of the numpy add function
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [10]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [12]:
vector = np.arange(10, 50)
reversed_vector = vector[::-1]
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [14]:
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
print(non_zero_indices)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [15]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [16]:
array = np.random.random((3, 3, 3))
print(array)

[[[0.01968948 0.87969058 0.38577972]
  [0.13419112 0.96724013 0.42310628]
  [0.89815388 0.50188035 0.17303466]]

 [[0.2606335  0.03086249 0.98219664]
  [0.05955807 0.66039609 0.0629937 ]
  [0.54143207 0.75534109 0.77783664]]

 [[0.08291389 0.44519422 0.45981902]
  [0.39188118 0.46778082 0.88980065]
  [0.38607971 0.2861147  0.93858826]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [17]:
array = np.random.random((10, 10))
print("Minimum:", np.min(array))
print("Maximum:", np.max(array))

Minimum: 0.000198715482888967
Maximum: 0.9986641246241983


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [18]:
vector = np.random.random(30)
mean_value = np.mean(vector)
print(mean_value)

0.5215108711704837


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [19]:
array = np.ones((5, 5))
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [20]:
array = np.ones((5, 5))
array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(array)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [21]:
print(0 * np.nan)         # nan
print(np.nan == np.nan)   # False
print(np.inf > np.nan)    # False
print(np.nan - np.nan)    # nan
print(np.nan in set([np.nan]))  # True
print(0.3 == 3 * 0.1)     # False

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [22]:
matrix = np.diag(1 + np.arange(4), k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [23]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [24]:
shape = (6, 7, 8)
index = np.unravel_index(100, shape)
print(index)

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [25]:
checkerboard = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [26]:
matrix = np.random.random((5, 5))
normalized_matrix = (matrix - np.mean(matrix)) / np.std(matrix)
print(normalized_matrix)

[[-0.35107541 -0.61844791  0.45793662 -0.07120569  1.72854299]
 [-0.10533123 -0.08994994 -0.59374949 -0.01875703 -0.70502839]
 [-0.12735062  1.47772571  0.74952752 -1.52494319  0.39752415]
 [ 1.12999084 -1.79432203  0.38347427 -1.34075976  0.54908411]
 [ 1.83211002  0.82167153 -1.01040613 -1.74791276  0.5716518 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [27]:
color_dtype = np.dtype([('R', np.ubyte),
                        ('G', np.ubyte),
                        ('B', np.ubyte),
                        ('A', np.ubyte)])
print(color_dtype)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [28]:
matrix1 = np.random.random((5, 3))
matrix2 = np.random.random((3, 2))
result = np.dot(matrix1, matrix2)
print(result)

[[0.83073911 1.18009508]
 [1.1096787  1.59547923]
 [0.80011174 1.08312984]
 [0.68511788 0.89684029]
 [0.4974942  0.74041669]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [29]:
arr = np.arange(11)
arr[(3 < arr) & (arr <= 8)] *= -1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [30]:
print(sum(range(5), -1))  # 9
from numpy import *
print(sum(range(5), -1))  # 10

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [31]:
Z = np.arange(5)
print(Z**Z)       # Legal
print(2 << Z >> 2) # Legal
print(Z <- Z)      # Legal
print(1j*Z)        # Legal
print(Z/1/1)       # Legal
print(Z<Z>Z)       # Illegal

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [32]:
print(np.array(0) / np.array(0))                # nan
print(np.array(0) // np.array(0))               # 0
print(np.array([np.nan]).astype(int).astype(float))  # [-2.14748365e+09]

nan
0
[-2.14748365e+09]


C:\Users\2189v\AppData\Local\Temp\ipykernel_12740\3492719885.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))                # nan
C:\Users\2189v\AppData\Local\Temp\ipykernel_12740\3492719885.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))               # 0


#### 29. How to round away from zero a float array ? (★☆☆)

In [33]:
arr = np.random.uniform(-10, 10, 10)
rounded_arr = np.copysign(np.ceil(np.abs(arr)), arr)
print(rounded_arr)

[ 8. -5.  3. -2. -9.  2. -6.  3. -4. -1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [34]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])
common_values = np.intersect1d(array1, array2)
print(common_values)

[3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [35]:
import warnings
warnings.filterwarnings('ignore', category=np.VisibleDeprecationWarning)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [36]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\2189v\AppData\Local\Temp\ipykernel_12740\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [37]:
import datetime

today = datetime.date.today()
yesterday = today - datetime.timedelta(days=1)
tomorrow = today + datetime.timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2024-07-22
Today: 2024-07-23
Tomorrow: 2024-07-24


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [38]:
import numpy as np

dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [39]:
import numpy as np

A = np.random.rand(5, 5)
B = np.random.rand(5, 5)

np.multiply(np.add(A, B), np.negative(np.divide(A, 2)), out=A)
print(A)

[[-0.73512239 -0.01022427 -0.14674211 -0.2935875  -0.22057755]
 [-0.23605631 -0.41390433 -0.02118563 -0.65543506 -0.17655511]
 [-0.59363657 -0.05333227 -0.15016892 -0.09768535 -0.59086145]
 [-0.04313483 -0.38753852 -0.68750444 -0.64744759 -0.12427358]
 [-0.23306513 -0.02928847 -0.49166549 -0.82176386 -0.47933108]]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [40]:
arr = np.random.uniform(0, 10, 10)

# 1. Truncate method
print(arr // 1)

# 2. Floor method
print(np.floor(arr))

# 3. Ceil method
print(np.ceil(arr) - 1)

# 4. Casting to integer
print(arr.astype(int))

[7. 1. 1. 9. 5. 9. 6. 2. 6. 6.]
[7. 1. 1. 9. 5. 9. 6. 2. 6. 6.]
[7. 1. 1. 9. 5. 9. 6. 2. 6. 6.]
[7 1 1 9 5 9 6 2 6 6]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [41]:
arr = np.zeros((5, 5))
arr += np.arange(5)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [42]:
def generator():
    for i in range(10):
        yield i

arr = np.fromiter(generator(), dtype=int)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [43]:
arr = np.linspace(0, 1, 12)[1:-1]
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [44]:
arr = np.random.rand(10)
arr.sort()
print(arr)

[0.12471208 0.29450489 0.36901835 0.39356939 0.55976738 0.62304038
 0.69921006 0.71428495 0.86004957 0.92314022]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [45]:
arr = np.arange(10)

# Faster way using np.add.reduce
sum_value = np.add.reduce(arr)
print(sum_value)

45


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [46]:
A = np.random.rand(5)
B = np.random.rand(5)

equal = np.array_equal(A, B)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [47]:
arr = np.zeros(10)
arr.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [48]:
Z = np.random.random((10,2))
X, Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)
print(R)
print(T)

[0.99208718 1.04147118 0.56737223 1.19770084 0.47033855 0.83468351
 0.65411824 0.51699111 1.28396983 0.73283293]
[0.33696063 0.8582649  0.24986396 0.76133619 0.76632268 1.46825068
 0.54798137 1.00040853 0.79025811 1.01410135]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [49]:
arr = np.random.rand(10)
arr[arr.argmax()] = 0
print(arr)

[0.71536332 0.85717404 0.45999448 0.12316308 0.41769741 0.17641382
 0.24784216 0.61031207 0.         0.68242445]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [50]:
arr = np.zeros(10, [ ('x', float), ('y', float) ])
arr['x'], arr['y'] = np.random.rand(2, 10)
print(arr)

[(0.64752814, 0.79623761) (0.42892218, 0.61485719)
 (0.11303692, 0.65703785) (0.40837823, 0.2109802 )
 (0.81480582, 0.785299  ) (0.61069012, 0.19228029)
 (0.91999479, 0.04682049) (0.96098486, 0.9346824 )
 (0.60062757, 0.78795789) (0.31641799, 0.17110844)]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [51]:
X = np.random.rand(3)
Y = np.random.rand(3)
C = 1.0 / np.subtract.outer(X, Y)
print(C)

[[ 9.48858772 14.4315144   1.40563062]
 [11.78901502 20.52218114  1.44747247]
 [ 6.83266175  9.06956406  1.32909698]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [52]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [53]:
np.set_printoptions(threshold=float('inf'))
arr = np.zeros((16,16))
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [54]:
arr = np.arange(100)
value = np.random.uniform(0, 100)
index = (np.abs(arr - value)).argmin()
closest_value = arr[index]
print(closest_value)

42


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [55]:
import numpy as np

# Define the dtype for structured array
dtype = [('position', [('x', float), ('y', float)]),
         ('color', [('r', int), ('g', int), ('b', int)])]

# Create a structured array
arr = np.array([((1.0, 2.0), (255, 0, 0)),
                ((3.5, 4.1), (0, 128, 255))], dtype=dtype)

print(arr)

[((1. , 2. ), (255,   0,   0)) ((3.5, 4.1), (  0, 128, 255))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [56]:
import numpy as np

# Generate random coordinates
coords = np.random.random((100, 2))

# Compute pairwise distances using broadcasting
distances = np.sqrt(np.sum((coords[:, np.newaxis, :] - coords[np.newaxis, :, :]) ** 2, axis=-1))

print(distances)

[[0.         0.30667051 0.63222665 0.79905063 0.94218595 0.45419747
  0.91587237 0.59678037 1.00841849 0.45370897 1.06649477 0.51559238
  0.43610251 0.28367178 0.96529707 0.81993038 0.7893991  0.69950257
  0.85715966 0.59512273 0.04344778 0.49342394 0.82266666 0.90283016
  0.29574287 0.48401467 0.74976804 0.33757462 0.4151548  0.40177087
  0.69700523 1.18082522 0.2981767  0.75481739 0.94674804 0.53870207
  0.49855094 0.76283637 0.27900627 0.80088749 0.81847275 0.70853985
  0.62986558 0.80727012 0.07423027 0.58221347 0.82613687 0.5873864
  0.56642615 0.20993768 1.02216084 0.43095962 0.68886031 0.62313516
  0.38104348 0.75238185 0.43872938 0.98282519 0.55578937 0.89677746
  0.73012286 0.88973636 0.20655904 0.44699313 0.7313436  0.66432613
  0.55368819 0.8697996  0.28002557 1.03472897 0.45869579 0.97437617
  0.74733429 0.79145134 0.86850224 0.99566313 0.46899063 0.25171386
  0.35720789 1.1146088  0.66918327 0.23816295 0.13841094 0.20413376
  0.297017   0.60396738 0.42139493 0.67502594 0.1

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [57]:
import numpy as np

# Create a float32 array
arr_float = np.array([1.5, 2.7, 3.1], dtype=np.float32)

# Convert to int32 in place
arr_float.view(dtype=np.int32)[:] = arr_float

print(arr_float)

[1.e-45 3.e-45 4.e-45]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

SyntaxError: invalid syntax (2460604331.py, line 2)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [59]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])

for index, value in np.ndenumerate(arr):
    print(index, value)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [60]:
import numpy as np

def gaussian_2d(shape=(256, 256), sigma=10):
    m, n = [(ss - 1.)/2. for ss in shape]
    y, x = np.ogrid[-m:m+1,-n:n+1]
    h = np.exp(-(x*x + y*y) / (2.*sigma*sigma))
    h[h < np.finfo(h.dtype).eps*h.max()] = 0
    return h

gaussian_array = gaussian_2d()

print(gaussian_array)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.0000

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [61]:
import numpy as np

# Example 2D array
arr = np.zeros((5, 5), dtype=int)
p = 6  # Number of elements to place

# Generate random indices within array bounds
indices = np.random.choice(range(25), p, replace=False)
row_indices, col_indices = np.unravel_index(indices, arr.shape)

# Assign random values to these indices
arr[row_indices, col_indices] = np.random.randint(1, 10, p)

print(arr)

[[0 0 1 0 9]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 4 6]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [62]:
import numpy as np

# Example matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Subtract mean of each row
mean_subtracted = matrix - np.mean(matrix, axis=1, keepdims=True)

print(mean_subtracted)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


#### 59. How to sort an array by the nth column? (★★☆)

In [63]:
import numpy as np

# Example array
arr = np.array([[1, 4, 2],
                [3, 1, 7],
                [2, 5, 3]])

# Sort by the second column (index 1)
sorted_arr = arr[arr[:, 1].argsort()]

print(sorted_arr)

[[3 1 7]
 [1 4 2]
 [2 5 3]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [64]:
import numpy as np

# Example array
arr = np.array([[1, 0, 3],
                [0, 0, 0],
                [4, 0, 6]])

# Check if any column is all zeros
null_columns = np.all(arr == 0, axis=0)

print(null_columns)

[False  True False]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [65]:
import numpy as np

# Example array
arr = np.array([1, 3, 5, 7, 9])

# Given value
value = 6

# Find nearest value
nearest_value = arr[np.argmin(np.abs(arr - value))]

print(nearest_value)

5


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [66]:
import numpy as np

# Example arrays
a = np.array([[1, 2, 3]])
b = np.array([[4],
              [5],
              [6]])

# Using np.nditer to iterate over elements
iterator = np.nditer([a, b])

sum_result = 0
for x, y in iterator:
    sum_result += x + y

print(sum_result)

63


#### 63. Create an array class that has a name attribute (★★☆)

In [67]:
import numpy as np

class NamedArray(np.ndarray):
    def __new__(cls, array, name="Unnamed"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', 'Unnamed')

# Example usage:
arr = NamedArray(np.arange(10), name="Example Array")
print(arr.name)  # Output: Example Array
print(arr)       # Output: [0 1 2 3 4 5 6 7 8 9]

Example Array
[0 1 2 3 4 5 6 7 8 9]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [74]:
v1 = [10, 20, 30, 40, 50]
v2 = [1, 3, 1, 4]

v3 = []
for i in v2:
    v3.append(v1[i-1] + 1)

print(v3)  # Çıktı: [11, 21, 31, 41]

[11, 31, 11, 41]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [76]:
X = [10, 20, 30, 40, 50]
I = [1, 3, 1, 4, 2]

F = [0] * len(set(I))  # Boş F dizisini oluşturma
for i, x in enumerate(X):
    F[I[i]-1] = x  # I'daki indeks 1'den başladığı için 1 çıkarılır

print(F)  # Çıktı: [10, 20, 30, 50]

[30, 50, 20, 40]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [77]:
import numpy as np

# Example image with shape (w, h, 3)
image = np.random.randint(0, 256, size=(10, 10, 3), dtype=np.uint8)  # Example image

# Reshape the image to (w*h, 3) and find unique colors
unique_colors = np.unique(image.reshape(-1, 3), axis=0)

num_unique_colors = len(unique_colors)

print(f"Number of unique colors: {num_unique_colors}")

Number of unique colors: 100


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [78]:
import numpy as np

# Example 4D array
arr = np.random.randint(0, 10, size=(2, 3, 4, 5))

# Sum over the last two axes
sum_result = np.sum(arr, axis=(-1, -2))

print("Original array shape:", arr.shape)
print("Sum along the last two axes shape:", sum_result.shape)
print(sum_result)

Original array shape: (2, 3, 4, 5)
Sum along the last two axes shape: (2, 3)
[[94 85 93]
 [92 92 88]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [79]:
import numpy as np

# Example vector D and index vector S
D = np.array([1, 2, 3, 4, 5, 6])
S = np.array([0, 1, 0, 1, 2, 2])

# Get unique indices and counts
unique_indices, counts = np.unique(S, return_counts=True)

# Compute mean of subsets
subset_means = np.bincount(S, weights=D) / counts

print("Subset means:", subset_means)

Subset means: [2.  3.  5.5]


#### 69. How to get the diagonal of a dot product? (★★★)

In [80]:
import numpy as np

# Example arrays
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# Dot product of A and B
dot_product = np.dot(A, B)

# Diagonal elements of the dot product
diagonal_elements = np.diag(dot_product)

print("Dot product:")
print(dot_product)
print("Diagonal elements:")
print(diagonal_elements)

Dot product:
[[19 22]
 [43 50]]
Diagonal elements:
[19 50]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [81]:
import numpy as np

# Example vector
v = np.array([1, 2, 3, 4, 5])

# Insert 3 zeros between each element
result = np.zeros(len(v) + (len(v)-1)*3, dtype=v.dtype)
result[::4] = v

print("Resulting vector:")
print(result)

Resulting vector:
[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [82]:
import numpy as np

# Create a sample 3D array
arr_3d = np.random.randint(0, 10, size=(5, 5, 3))

# Create a 2D array of shape (5,5)
arr_2d = np.random.randint(0, 10, size=(5, 5))

# Broadcast the 2D array to match the shape of the 3D array
broadcasted_arr = arr_2d[:, :, np.newaxis] * arr_3d

print("3D Array (5,5,3):")
print(arr_3d)
print("\n2D Array (5,5):")
print(arr_2d)
print("\nBroadcasted Result (5,5,3):")
print(broadcasted_arr)

3D Array (5,5,3):
[[[3 1 0]
  [9 3 4]
  [9 8 3]
  [4 2 5]
  [1 3 1]]

 [[8 2 7]
  [8 6 8]
  [3 1 8]
  [2 7 0]
  [3 2 6]]

 [[2 8 9]
  [7 1 1]
  [5 5 3]
  [7 7 8]
  [4 7 1]]

 [[3 1 5]
  [7 2 0]
  [7 3 6]
  [0 4 6]
  [4 7 4]]

 [[3 6 6]
  [9 4 7]
  [0 1 9]
  [1 8 9]
  [5 3 5]]]

2D Array (5,5):
[[4 8 1 1 6]
 [6 0 4 8 9]
 [3 2 3 2 2]
 [1 3 8 6 0]
 [5 4 8 2 9]]

Broadcasted Result (5,5,3):
[[[12  4  0]
  [72 24 32]
  [ 9  8  3]
  [ 4  2  5]
  [ 6 18  6]]

 [[48 12 42]
  [ 0  0  0]
  [12  4 32]
  [16 56  0]
  [27 18 54]]

 [[ 6 24 27]
  [14  2  2]
  [15 15  9]
  [14 14 16]
  [ 8 14  2]]

 [[ 3  1  5]
  [21  6  0]
  [56 24 48]
  [ 0 24 36]
  [ 0  0  0]]

 [[15 30 30]
  [36 16 28]
  [ 0  8 72]
  [ 2 16 18]
  [45 27 45]]]


#### 72. How to swap two rows of an array? (★★★)

In [83]:
import numpy as np

# Create a sample array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Swap rows 0 and 1
arr[[0, 1]] = arr[[1, 0]]

print("Swapped Array:")
print(arr)

Swapped Array:
[[4 5 6]
 [1 2 3]
 [7 8 9]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [85]:
triangles = [
    [(0, 0), (2, 0), (1, 2)],
    [(1, 0), (3, 0), (2, 2)],
    [(2, 0), (4, 0), (3, 2)],
    [(3, 0), (5, 0), (4, 2)],
    [(4, 0), (6, 0), (5, 2)],
    [(0, 2), (2, 2), (1, 4)],
    [(1, 2), (3, 2), (2, 4)],
    [(2, 2), (4, 2), (3, 4)],
    [(3, 2), (5, 2), (4, 4)],
    [(4, 2), (6, 2), (5, 4)]
]

In [86]:
def find_unique_lines(triangles):
    lines = set()
    for triangle in triangles:
        for i in range(3):
            p1 = triangle[i]
            p2 = triangle[(i + 1) % 3]
            lines.add(tuple(sorted([p1, p2])))
    return lines

unique_lines = find_unique_lines(triangles)
print(unique_lines)

{((2, 4), (3, 2)), ((3, 2), (5, 2)), ((1, 0), (3, 0)), ((0, 0), (2, 0)), ((2, 2), (4, 2)), ((2, 0), (3, 2)), ((4, 0), (5, 2)), ((4, 0), (6, 0)), ((3, 4), (4, 2)), ((0, 2), (1, 4)), ((2, 0), (4, 0)), ((3, 0), (4, 2)), ((3, 2), (4, 4)), ((1, 4), (2, 2)), ((4, 4), (5, 2)), ((5, 2), (6, 0)), ((4, 2), (5, 4)), ((5, 4), (6, 2)), ((1, 2), (2, 4)), ((3, 2), (4, 0)), ((3, 0), (5, 0)), ((0, 2), (2, 2)), ((0, 0), (1, 2)), ((2, 2), (3, 4)), ((4, 2), (6, 2)), ((4, 2), (5, 0)), ((1, 0), (2, 2)), ((1, 2), (3, 2)), ((1, 2), (2, 0)), ((2, 2), (3, 0))}


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [87]:
import numpy as np

# Example sorted array C
C = np.array([0, 1, 1, 2, 2, 3, 3, 3])

# Generate array A
A = np.repeat(np.arange(len(C)), C)

# Check if np.bincount(A) matches C
assert np.array_equal(np.bincount(A), C)

print("Array A:", A)

Array A: [1 2 3 3 4 4 5 5 5 6 6 6 7 7 7]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [88]:
import numpy as np

# Example array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Define window size
window_size = 3

# Compute rolling averages
rolling_avg = np.convolve(arr, np.ones(window_size)/window_size, mode='valid')

print("Original array:", arr)
print("Rolling averages (window size", window_size, "):", rolling_avg)

Original array: [ 1  2  3  4  5  6  7  8  9 10]
Rolling averages (window size 3 ): [2. 3. 4. 5. 6. 7. 8. 9.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [89]:
import numpy as np

# Example 1D array
Z = np.array([1, 2, 3, 4, 5])

# Create 2D array with shifted rows
shifted_array = np.vstack([Z[i:i+3] for i in range(len(Z)-2)])

print("Original 1D array:", Z)
print("Shifted 2D array:")
print(shifted_array)

Original 1D array: [1 2 3 4 5]
Shifted 2D array:
[[1 2 3]
 [2 3 4]
 [3 4 5]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [90]:
# Negating a boolean variable
bool_var = True
negated_bool = not bool_var
print("Negated boolean:", negated_bool)

# Toggling an integer using bitwise negation (~)
integer_flag = 0
toggled_flag = ~integer_flag
print("Toggled flag:", toggled_flag)

Negated boolean: False
Toggled flag: -1


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [91]:
import numpy as np

def distance_point_to_line_segment(p, P0, P1):
    # Convert inputs to numpy arrays
    p = np.array(p)
    P0 = np.array(P0)
    P1 = np.array(P1)
    
    # Vector P0 to P1
    v = P1 - P0
    
    # Vector P0 to p
    w = p - P0
    
    # Projection of w onto v
    t = np.dot(w, v) / np.dot(v, v)
    t = np.clip(t, 0, 1)  # Clip to ensure projection falls within the segment
    
    # Closest point on the line segment
    closest_point = P0 + t * v
    
    # Distance from p to closest_point
    distance = np.linalg.norm(p - closest_point)
    
    return distance

# Example usage:
p = [0, 0]  # Point p
P0 = [[1, 1], [2, 2]]  # Start points of line segments
P1 = [[3, 3], [4, 4]]  # End points of line segments

# Compute distances
distances = [distance_point_to_line_segment(p, P0[i], P1[i]) for i in range(len(P0))]
print("Distances to line segments:", distances)

Distances to line segments: [1.4142135623730951, 2.8284271247461903]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [92]:
def distances_from_points_to_lines(P, P0, P1):
    distances = []
    for point in P:
        distances.append([distance_point_to_line_segment(point, P0[i], P1[i]) for i in range(len(P0))])
    return np.array(distances)

# Example usage:
P = [[0, 0], [1, 1]]  # Set of points
P0 = [[1, 1], [2, 2]]  # Start points of line segments
P1 = [[3, 3], [4, 4]]  # End points of line segments

# Compute distances
distances = distances_from_points_to_lines(P, P0, P1)
print("Distances from points to lines:")
print(distances)

Distances from points to lines:
[[1.41421356 2.82842712]
 [0.         1.41421356]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [93]:
def extract_subpart_centered(arr, center, shape, fill_value=0):
    center_x, center_y = center
    size_x, size_y = shape
    half_size_x, half_size_y = size_x // 2, size_y // 2
    
    # Calculate slicing bounds
    start_x = max(0, center_x - half_size_x)
    end_x = min(arr.shape[0], center_x + half_size_x + 1)
    start_y = max(0, center_y - half_size_y)
    end_y = min(arr.shape[1], center_y + half_size_y + 1)
    
    # Extract the subpart
    subpart = arr[start_x:end_x, start_y:end_y].copy()
    
    # Pad if necessary
    pad_width_x = ((start_x, max(0, size_x - subpart.shape[0])), (0, 0))
    pad_width_y = ((0, 0), (start_y, max(0, size_y - subpart.shape[1])))
    subpart = np.pad(subpart, pad_width_x, mode='constant', constant_values=fill_value)
    subpart = np.pad(subpart, pad_width_y, mode='constant', constant_values=fill_value)
    
    return subpart

# Example usage:
arr = np.random.randint(0, 10, (10, 10))  # Example array
center = (5, 5)  # Center point
shape = (3, 3)  # Shape of the subpart

subpart = extract_subpart_centered(arr, center, shape)
print("Original array:")
print(arr)
print("Extracted subpart centered on", center, "with shape", shape, ":")
print(subpart)

Original array:
[[1 0 1 2 7 9 2 5 5 9]
 [7 1 8 9 6 6 8 8 1 2]
 [9 6 2 2 4 9 3 4 7 1]
 [1 6 4 0 5 1 7 0 4 2]
 [1 1 0 6 3 3 1 1 7 6]
 [4 7 3 3 7 6 8 8 5 9]
 [8 6 5 4 5 4 7 8 7 9]
 [5 6 6 3 9 5 7 3 8 7]
 [3 5 4 5 1 0 3 0 2 8]
 [6 5 9 2 5 1 3 1 2 3]]
Extracted subpart centered on (5, 5) with shape (3, 3) :
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 3 3 1]
 [0 0 0 0 7 6 8]
 [0 0 0 0 5 4 7]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [94]:
R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]

In [95]:
import numpy as np

Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])

# Using list comprehension
window_size = 4
R = [Z[i:i+window_size] for i in range(len(Z)-window_size+1)]

print("Array Z:", Z)
print("Array R:")
print(R)

Array Z: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Array R:
[array([1, 2, 3, 4]), array([2, 3, 4, 5]), array([3, 4, 5, 6]), array([4, 5, 6, 7]), array([5, 6, 7, 8]), array([6, 7, 8, 9]), array([ 7,  8,  9, 10]), array([ 8,  9, 10, 11]), array([ 9, 10, 11, 12]), array([10, 11, 12, 13]), array([11, 12, 13, 14])]


#### 82. Compute a matrix rank (★★★)

In [96]:
import numpy as np

# Example matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Compute rank
rank = np.linalg.matrix_rank(A)

print("Matrix A:")
print(A)
print("Rank of A:", rank)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Rank of A: 2


#### 83. How to find the most frequent value in an array?

In [97]:
import numpy as np
from collections import Counter

# Example array
arr = np.array([1, 2, 3, 1, 2, 2, 3, 1, 3, 3, 3])

# Using numpy and Counter
most_common_value = Counter(arr).most_common(1)[0][0]

print("Array:", arr)
print("Most frequent value:", most_common_value)

Array: [1 2 3 1 2 2 3 1 3 3 3]
Most frequent value: 3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [98]:
import numpy as np

# Example random 10x10 matrix
matrix = np.random.randint(0, 10, (10, 10))

# Parameters
block_size = 3
stride = matrix.strides

# Generate all 3x3 blocks
blocks = np.lib.stride_tricks.as_strided(matrix, shape=(8, 8, block_size, block_size),
                                         strides=(stride[0], stride[1], stride[0], stride[1]))

print("Original Matrix:")
print(matrix)
print("All 3x3 blocks:")
print(blocks)

Original Matrix:
[[1 2 9 1 0 0 0 8 5 5]
 [0 5 0 7 2 2 1 7 3 6]
 [0 9 7 7 5 6 9 1 5 5]
 [2 6 2 1 2 1 9 0 9 5]
 [6 6 8 9 5 3 9 9 8 2]
 [9 6 0 3 6 2 1 5 0 2]
 [0 3 6 5 5 7 0 6 0 5]
 [3 4 1 7 4 1 5 6 5 8]
 [3 6 4 8 9 0 5 8 4 6]
 [6 1 0 6 9 6 9 9 7 8]]
All 3x3 blocks:
[[[[1 2 9]
   [0 5 0]
   [0 9 7]]

  [[2 9 1]
   [5 0 7]
   [9 7 7]]

  [[9 1 0]
   [0 7 2]
   [7 7 5]]

  [[1 0 0]
   [7 2 2]
   [7 5 6]]

  [[0 0 0]
   [2 2 1]
   [5 6 9]]

  [[0 0 8]
   [2 1 7]
   [6 9 1]]

  [[0 8 5]
   [1 7 3]
   [9 1 5]]

  [[8 5 5]
   [7 3 6]
   [1 5 5]]]


 [[[0 5 0]
   [0 9 7]
   [2 6 2]]

  [[5 0 7]
   [9 7 7]
   [6 2 1]]

  [[0 7 2]
   [7 7 5]
   [2 1 2]]

  [[7 2 2]
   [7 5 6]
   [1 2 1]]

  [[2 2 1]
   [5 6 9]
   [2 1 9]]

  [[2 1 7]
   [6 9 1]
   [1 9 0]]

  [[1 7 3]
   [9 1 5]
   [9 0 9]]

  [[7 3 6]
   [1 5 5]
   [0 9 5]]]


 [[[0 9 7]
   [2 6 2]
   [6 6 8]]

  [[9 7 7]
   [6 2 1]
   [6 8 9]]

  [[7 7 5]
   [2 1 2]
   [8 9 5]]

  [[7 5 6]
   [1 2 1]
   [9 5 3]]

  [[5 6 9]
   [2 1 9]
   [5 3 9]

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [99]:
import numpy as np

# Define the subclass
class SymmetricArray(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super(SymmetricArray, self).__setitem__((i, j), value)
        super(SymmetricArray, self).__setitem__((j, i), value)

# Example usage
Z = np.zeros((5, 5), dtype=int)
sym_array = SymmetricArray(Z)

# Setting values
sym_array[1, 2] = 5
sym_array[2, 1] = 5

print("Symmetric Array:")
print(sym_array)

TypeError: only integer scalar arrays can be converted to a scalar index

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
import numpy as np

# Example matrices and vectors
p = 3
n = 4
matrices = np.random.randint(0, 10, size=(p, n, n))
vectors = np.random.randint(0, 10, size=(p, n, 1))

# Compute sum of matrix products
sum_products = np.sum(np.matmul(matrices, vectors), axis=0)

print("Matrices:")
print(matrices)
print("Vectors:")
print(vectors)
print("Sum of matrix products:")
print(sum_products)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
import numpy as np

# Example 16x16 array
arr = np.random.randint(1, 10, size=(16, 16))

# Block size
block_size = 4

# Reshape and sum blocks
block_sums = np.add.reduceat(np.add.reduceat(arr, np.arange(0, arr.shape[0], block_size), axis=0),
                             np.arange(0, arr.shape[1], block_size), axis=1)

print("Original 16x16 Array:")
print(arr)
print("Block sums ({}x{} blocks):".format(block_size, block_size))
print(block_sums)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

def update(frameNum, img, grid, N):
    new_grid = grid.copy()
    for i in range(N):
        for j in range(N):
            # Count live neighbors
            neighbors = grid[(i-1):(i+2), (j-1):(j+2)].sum() - grid[i, j]
            
            # Apply rules
            if grid[i, j] == 1 and (neighbors < 2 or neighbors > 3):
                new_grid[i, j] = 0
            elif grid[i, j] == 0 and neighbors == 3:
                new_grid[i, j] = 1
    
    img.set_data(new_grid)
    grid[:] = new_grid[:]
    return img,

# Example initial state
N = 50
grid = np.random.choice([0, 1], size=(N, N), p=[0.5, 0.5])

fig, ax = plt.subplots()
img = ax.imshow(grid, interpolation='nearest')
ani = animation.FuncAnimation(fig, update, fargs=(img, grid, N), frames=10, interval=200, save_count=50)

plt.show()

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)